#!/usr/bin/env python
# coding: utf-8

"""Construct an online French-speaking Chatterbot
to help out the new students at the LTTAC 
Master's degree (Lille, France) having a hard time
understanding the complex terminology behind it.
"""

# import files
from flask import Flask, render_template, request
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.response_selection import get_most_frequent_response

bot = ChatBot("LTTAC_professor", # Initializations
              response_selection_method=get_most_frequent_response, # When in doubt, find the most common answer
              storage_adapter='chatterbot.storage.SQLStorageAdapter',
              database_uri='sqlite:///database.sqlite3',
              logic_adapters=[
                  {
                      'import_path': 'chatterbot.logic.BestMatch',
                      "statement_comparison_function": 'chatterbot.comparisons.levenshtein_distance', # Initialization of the Levenshtein distance
                      'default_response': 'Je suis désolé mais je ne comprends pas la question.' # Default answer in case of doubt
                  }
              ]
            )

ChatterBotCorpusTrainer(bot).train('chatterbot.corpus.french') # Corpus-based training to teach the bot LTTAC-related terms
from chatterbot.trainers import ListTrainer

ListTrainer(bot).train([ # LTTAC corpus
"Bonjour.",
"Salut !",
"C'est quoi un composant de traitement ?",
"Dans un article, le composant de traitement est le bloc structurel dédié à la strate sémantique de l’item en adresse, donc à sa définition, et à sa contextualisation. Ce composant est relativement dense puisqu’il énonce et précise se(s) sens. En cela, il constitue le cœur de l’article en exposant les informations sémantiques et contextuelles nécessaires à connaître pour comprendre et employer une unité linguistique donnée.",
"C'est quoi un composant d'identification ?",
"Dans un article, le composant d'identification est le bloc structurel dédié à la présentation de la graphie de l’item en adresse (sa forme écrite), à sa prononciation (facultative), à sa catégorisation et, parfois, à son étymologie.",
"C'est quoi un item en adresse ?",
"C'est l'unité linguistique définie dans un article dédié. La codification typographique sert usuellement à mettre en relief son orthographe et sa position, au début de l’article.",
"C'est quoi la rection d'un verbe ?",
"Cela concerne la nature des compléments attendus par le verbe. Le plus souvent, on trouvera les mentions transitif et intransitif.",
"C'est quoi la catégorisation ?",
"La catégorisation est la catégorie grammaticale et, optionnellement, genre, transitivité et/ou rection verbales, ainsi que les caractéristiques irrégulières importantes à noter pour définir une unité linguistique. Conventionnellement, ces informations apparaissent après l’item en adresse, souvent sous forme abrégée, notamment en version papier. Elles peuvent également s’accumuler, alors disjointes par un séparateur, comme c’est le cas pour les unités linguistiques étant à la fois des noms et des adjectifs.",
"C'est quoi s.v. ?",
"Cela est une abréviation latine permettant de renvoyer à un article voire à une section de cet article.",
"C'est quoi une sous-adresse ?",
"Une sous-adresse est un item en adresse défini dans un autre article (dit principal).",
"C'est quoi contextualisation ?",
"Une contextualisation est un syntagme, une proposition ou une phrase qui met en contexte le sens traité d’une unité linguistique donnée. Il peut s’agir d’une citation, si le rédacteur le juge pertinent. ",
"C'est quoi une glose ?",
"Une glose est une phrase définitionnelle qui suit une phrase contextualisante. Les deux sont séparées par une virgule, montrant ainsi que la seconde explique la première. La virgule est, dans ce cas, un coordinateur.",
"C'est quoi étymon ?",
"L'étymon est un mot dont est issu l'étymologie d'un autre mot.",
"C'est quoi un syntagme ?",
"Un syntagme est un groupe de mots dont l'un d'eux en est la tête et détermine la nature du syntagme. Par exemple, si la tête d'un syntagme est un verbe, on parlera de syntagme verbal.",
"C'est quoi la TEI ?",
"La TEI est une norme académique internationale de nommage et de strucuration XML.",
"À quoi réfère une clé de regroupement ?",
"Une clé de regroupement est une indication sémantique sur la division de traitement qu'elle chapeaute.",
"C'est quoi un renvoi ?",
"Un renvoi est un item valorisé typographiquement et/ou démarqué par la codification, invitant l’utilisateur à consulter l’article-cible. Celui-ci va souvent traiter d’une unité linguistique sémantiquement ou morphologiquement proche de l’item en adresse, apportant ainsi des précisions complémentaires ou annexes.",
"C'est quoi une locution ?",
"Une locution est un ensemble de mots figé qui peut s'utiliser comme tout autre mot.",
"C'est quoi néologisme ?",
"Un néologisme est un nouveau mot ou un nouveau sens d'un mot déjà existant.",
"C'est quoi nomenclature ?",
"La nomenclature d'un dictionnaire est l'ensemble des entrées principales constituant un répertoire lexical. Les critères de sélection de la nomenclature sont trois : linguistiques, pour élaborer un dictionnaire d’un certain type de discours ; socio-linguistiques, pour décrire les usages d’une aire géographique donnée, voire d’une entreprise ou d’un registre ; pratiques, pour référer à des données réelles courantes.",
"C'est quoi une information encyclopédique ?",
"Une information est de nature encyclopédique quand elle apporte des précisions concernant plus le référent que l'aspect sémantique de l'item en adresse.",
"C'est quoi une planche encyclopédique ?",
"Une planche encyclopédique regroupe souvent des dessins ou des schémas explicatifs sur l'item en adresse.",
"Qu'est qu'un mot-repère ?",
"Un mot-repère est le mot que l'on retoruve en haut des pages d'un dictionnaire. Quand il est en haut, à gauche, il s'avère du premier mot défini de la page. Quand il est en haut, à droite, il s'avère du dernier mot défini de la page.",
"Qu'est qu'un mot-vedette ?",
"Un mot-vedette est un item en adresse, soit le mot traité dans un article.",
"Que sont des mots paronymes ?",
"Des mots paronymes sont des mots ayant une consonnance si semblable que l'on pourrait les confondre.",
"C'est quoi un emprunt ?",
"Un emprunt est un mot qui vient d'une autre langue, qui lui est emprunté, et qui est utilisé tel quel.",
"C'est quoi codification typographique ?",
"Les moyens de codification typographiques englobent tout choix de mise en page, de police, de couleur, de degrés de graisse, qui fractionnent ou fluidifient les articles. (adaptés de Structurations formelle et conceptuelle des articles de dictionnaires : comparaison de codifications employées chez Larousse en 1856 et 1997, Corbin Pierre & Gasiglia Nathalie)",
"C'est quoi une attestation d'un mot ?",
"Une attestation d'un mot est un exemple de celui-ci en contexte.",
"C'est quoi une iconographie ?",
"C'est une image ou un dessin.",
"C'est quoi un régionalisme ?",
"C'est un mot qui est originaire et propre à une région.",
"C'est quoi une marque d'usage ?",
"Une marque d'usage est une indication sur la manière dont est employé l'item en adresse.",
"C'est quoi la métalangue ?",
"La métalangue d'un dictionnaire regroupe l'ensemble des mots employés pour définir et décrire les différentes unités lingusitiques.",
"C'est quoi l'A.P.I. ?",
"L'A.P.I. est l'alphabet phonétique international permettant d'écrire les mots tel qu'on les entend.",
"C'est quoi l'emploi d'un mot ?",
"L'emploi d'un mot est la façon dont il va être utilisé dans une phrase donnée.",
"C'est quoi un atlas ?",
"Un atlas contient souvent plusieurs cartes géographiques.",
"C'est quoi homographe ?",
"Deux mots sont homographes lorsque leurs graphies sont identiques.",
"C'est quoi une variante graphique ?",
"Si un mot s'écrit de différentes façons, on dira qu'il a plusieurs variantes graphiques.",
"C'est quoi un équivalent traductionnel ?",
"Un équivalent traductionnel d'un mot est son homologue dans une langue étrangère.",
"C'est quoi un renvoi analogique ?",
"Un renvoi analogique est l’item-cible lié morphologiquement à l’item-source par son référent et sens.",
"C'est quoi graphie d'un item donné ?",
"La graphie d'un item donné est sa forme écrite.",
"C'est quoi un métalangage ?",
"Un métalangage est employé dans le but d'analyser, d'expliquer et de rendre compte de la grammaire et de l'aspect sémantique d'une langue donnée, d'un langage donné.",
"C'est quoi une édition millésimée ?",
"Cela renvoie à un ouvrage dictionnairique édité annuellement et dont l'année de parution est mentionnée dans son titre, constituant, par la même occasion, un argument marketing.",
"C'est quoi la différence entre un composant de traitement et un composant d'identification ?",
"Un composant d'identification présente la graphie de l'item en adresse principale ainsi que sa catégorisation tandis qu'un composant de traitement contient, entre autre, une ou plusieurs définitions et des contextualisations.",
"C'est quoi la différence entre un article principal et un article subordonné ?",
"Un article principal traite l'item en adresse principal tandis qu'un article subordonné traite une sous-adresse, insérée dans l'article principal.",
"Quels sont les différents types de définition ?",
"Les différents types de définition sont : définition syntagmatique, exemple glosé, définition morphologique, définition phrastique, définition synonymique et définition métalinguistique.",
"À quoi servent les unités de traitement ?",
"Les unités de traitement servent à traiter différents sens au sein du composant de traitement.",
"C'est quoi les différentes fonctions de la ponctuation en lexicographie ?",
"La ponctuation peut être un coordinateur, un terminateur ou un séparateur.",
"C'est quoi la différence entre microstructure ou la macrostructure ?",
"La microstructure renvoie à l'organisation des éléments dans un composant de traitement alors que la macrostructure renvoie plus aux unités linguistiques présentes à la nomenclature.",
"Quelle différence y a-t-il entre exemple et contextualisation ?",
"Il n'y a aucune différence entre ces deux termes, ils sont synonymes.",
"Comment citer un article dans un texte ?",
"Pour citer un article dans un texte, on utilise s.v., en italique, suivi de l'item en adresse, en gras.",
"Comment citer une division d'un article ?",
"Pour citer une division d'un article dans un texte, on utilise s.v., en italique, suivi de l'item en adresse, en gras, puis du numéro de la division pointée.",
"C'est quoi acception ?",
"Signification qui varie selon le contexte où l’unité linguistique est employée. Un de ses sens peut être partagé dans une communauté et non dans une autre.",
"Que veut dire dans l'acception du terme ?",
"Cela signifie dans son plein sens.",
"C'est quoi l'adressage ?",
"L'adressage est un Composant d’articles qui structure et qui présente les éléments de la nomenclature, dans l’ordre alphabétique, le plus couramment. Ces éléments prennent une forme lemmatisée ou dictionnairique : au masculin singulier, pour les noms et les adjectifs, et à l’infinitif, pour verbes.",
"C'est quoi le co-adressage ?",
"C'est le composant qui regroupe des éléments de la nomenclature sémantiquement proches, des dérivés, par exemple. La définition qui suit les traite tous à la fois, de manière fluide et homogène.",
"C'est quoi le sous-adressage ?",
"C'est le composant qui englobe les items subordonnés à l’item en adresse, apparaissant au-dessous de celui-ci et faisant donc partie de la microstructure. Il peut contenir des dérivés morphologiques de l’item en adresse ou des unités linguistiques polylexicales l’ayant comme noyau lexical.",
"C'est quoi la différence entre le co-adressage et le sous-adressage ?",
"Le co-adressage est le composant qui regroupe des éléments de la nomenclature sémantiquement proches, des dérivés, par exemple. La définition qui suit les traite tous à la fois, de manière fluide et homogène. Le sous-adressage est le composant qui englobe les items subordonnés à l’item en adresse, apparaissant au-dessous de celui-ci et faisant donc partie de la microstructure. Il peut contenir des dérivés morphologiques de l’item en adresse ou des unités linguistiques polylexicales l’ayant comme noyau lexical.",
"Que sont les analyses structurelles de dictionnaires ?",
"C'est l'intitulé d’un des cours dispensés en Master LTTAC dans lequel les étudiants apprennent à comprendre la logique et l’agencement des divers éléments imputables aux dictionnaires et, plus particulièrement, aux articles les organisant. Les diverses microstructures pensées par les différents (méta-)lexicographes sont analysées et comparées afin de mettre en exergue leurs enchâssements. Ils y voient notamment leurs composants principaux ainsi que les différents symboles et codifications permettant de matérialiser leur hiérarchie. Ce cours est aussi appelé analyses structurelles dictionnairiques.",
"C'est quoi un article ?",
"Un article est une division de texte qui permet de vérifier l’orthographe et le(s) sens d’une unité linguistique. Il indique sa catégorisation, sa définition, le montre en contexte. Il peut aussi donner des informations supplémentaires comme des synonymes, des antonymes, des mots de même famille ou encore des remarques encyclopédiques. Ses données sont divisées par composant d’article. Un article est une unité simple de la nomenclature et donc de la macrostructure.",
"C'est quoi un sous-article ?",
"C'est une partie de texte descriptif située à la suite de l’article principal qui contient des informations supplémentaires à propos de l’entrée, de sa morphologie ou encore de ses collocations.",
"Qu'est que la recatégorisation ?",
"C'est la catégorie grammaticale et, optionnellement, genre, transitivité et/ou rection verbales, ainsi que les caractéristiques irrégulières importantes à noter pour définir une unité linguistique. Conventionnellement, ces informations apparaissent après l’item en adresse, souvent sous forme abrégée, notamment en version papier. Elles peuvent également s’accumuler, alors disjointes par un séparateur, comme c’est le cas pour les unités linguistiques étant à la fois des noms et des adjectifs.",
"C'est quoi la différence entre la catégorisation et la recatégorisation ?",
"La catégorisation est la catégorie grammaticale et, optionnellement, genre, transitivité et/ou rection verbales, ainsi que les caractéristiques irrégulières importantes à noter pour définir une unité linguistique. Conventionnellement, ces informations apparaissent après l’item en adresse, souvent sous forme abrégée, notamment en version papier. Elles peuvent également s’accumuler, alors disjointes par un séparateur, comme c’est le cas pour les unités linguistiques étant à la fois des noms et des adjectifs. La recatégorisation est la catégorie grammaticale et, optionnellement, genre, transitivité et/ou rection verbales, ainsi que les caractéristiques irrégulières importantes à noter pour définir une unité linguistique. Conventionnellement, ces informations apparaissent après l’item en adresse, souvent sous forme abrégée, notamment en version papier. Elles peuvent également s’accumuler, alors disjointes par un séparateur, comme c’est le cas pour les unités linguistiques étant à la fois des noms et des adjectifs.",
"C'est quoi une codification ?",
"Cela regroupe les symboles propres à un dictionnaire qui structurent ses articles, organisent les éléments de ceux-ci et simplifient la lecture globale. Il existe quatre moyens de les codifier : textuels, symboliques, graphématiques et typographiques. Ces moyens codificatoires sont conjoints et non exclusifs, c’est-à-dire qu’ils peuvent se combiner au sein d’un ouvrage.",
"C'est quoi les codifications textuels ?",
"Ils comptent, par exemple, tout raccourcissement du texte, en version papier notamment, dont les abréviations pour la catégorisation des unités linguistiques ou les marques en dia-.",
"C'est quoi les codification symboliques ?",
"Les moyens de codification symboliques sont les tirets, losanges, flèches ou autres symboles utilisés comme introducteurs ou séparateurs. Des chiffres ordonnateurs peuvent aussi introduire des parties d’article.",
"C'est quoi les codifications graphématiques ?",
"Les moyens de codification graphématiques comportent des oppositions majuscules-minuscules et les signes de ponctuation qui coordonnent, séparent ou relient les parties d’articles.",
"C'est quoi un composant ?",
"C'est un bloc structurel du traitement d’un des aspects développés de l’item en adresse. La nature du composant va donc varier selon les informations affiliées au bloc courant. Un article est très souvent partagé en deux supra-composants : le composant d’adressage et le composant de traitement.",
"C'est quoi un composant d'adressage ?",
"C'est le bloc structurel dédié à la présentation de la graphie de l’item en adresse (sa forme écrite), à sa prononciation (facultative), à sa catégorisation et, parfois, à son étymologie.",
"C'est quoi le composant de catégorisation ?",
"C'est le bloc structurel englobé dans le composant d’adressage précisant la catégorie grammaticale de l’item en adresse puis, généralement mais pas obligatoirement, soit son genre, soit sa rection.",
"C'est quoi un composant encyclopédique ?",
"C'est le bloc structurel, souvent placé en fin d’article et introduit par un symbole, apportant des informations annexes, plus en lien avec le référent, l’objet désigné par l’entrée, qu’avec la facette sémantique développée par le composant de traitement.",
"C'est quoi un composant étymologique ?",
"C'est le bloc structurel, souvent englobé dans le composant d’adressage, dans lequel est mentionnée l’origine de l’item en adresse. Il est très majoritairement constitué de son/ses étymon(s) suivi(s), parfois, de sa/leur glose. Il peut également contenir les langues dont sont issus originellement les étymons.",
"C'est quoi un composant de variante graphique ?",
"C'est le bloc structurel suivant généralement le composant de traitement et proposant une alternative graphique à la forme de l’item en adresse. Il va souvent être introduit par un symbole, propre à ce composant, et complété par la graphie additionnelle.",
"C'est quoi la particule dia ?",
"C'est le préfixe servant à confectionner des indications, souvent abrégées, qui précédent un composant de traitement et qui précisent certaines propriétés d’usage intrinsèques à l’item en adresse.",
"C'est quoi une marque diachronique ?",
"C'est une indication temporelle permettant de percevoir si l’item en adresse est toujours employé ou s’il est obsolète.",
"C'est quoi une marque diaphasique ?",
"C'est une indication sur le conditionnement de l’énonciation inter-personnelle. Aussi appelée marque de registre.",
"C'est quoi une marque diatechnique ?",
"C'est une indication sur la nature des contextes d’emploi de l’item en adresse. Aussi appelée marque domaniale.",
"C'est quoi une marque diatopique ?",
"C'est une indication géographique concernant le(s) lieu(x) où est plus spécifiquement employé l’item en adresse.",
"C'est quoi une marque de registre ?",
"C'est une indication sur le conditionnement de l’énonciation inter-personnelle. Aussi appelée marque diaphasique.",
"C'est quoi une marque domaniale ?",
"C'est une indication sur la nature des contextes d’emploi de l’item en adresse. Aussi appelée marque diatechnique.",
"C'est quoi un dictionnaire ?",
"C'est un ouvrage didactique constitué par un ensemble d’articles, rangés dans un ordre déterminé (le plus souvent alphabétique), dont l’entrée est représentée par la forme graphique d’un élément de la nomenclature. Il a pour objectif principal de définir tous les éléments qui le composent en leur attribuant des définitions et des informations sur chaque entrée.",
"C'est quoi un dictionnaire général ?",
"C'est un ouvrage qui a pour objectif de décrire et de permettre la compréhension des mots nommant le monde. Il doit également viser à renseigner sur leur utilisation. Aussi appelé dictionnaire de référence ou dictionnaire de langue.",
"C'est quoi un dictionnaire de référence ?",
"C'est un ouvrage qui a pour objectif de décrire et de permettre la compréhension des mots nommant le monde. Il doit également viser à renseigner sur leur utilisation. Aussi appelé dictionnaire général ou dictionnaire de langue.",
"C'est quoi un dictionnaire de langue ?",
"C'est un ouvrage qui a pour objectif de décrire et de permettre la compréhension des mots nommant le monde. Il doit également viser à renseigner sur leur utilisation. Aussi appelé dictionnaire général ou dictionnaire de référence.",
"C'est quoi un dictionnaire spécialisé ?",
"C'est un ouvrage qui a pour objet un domaine particulier de la connaissance. Par exemple, contrairement au dictionnaire général, le dictionnaire encyclopédique associe répertoires lexicaux et répertoires non linguistiques, c’est-à-dire culturels.",
"C'est quoi un dictionnaire monolingue ?",
"C'est un ouvrage monofonctionnel qui ne concerne, ne traite et n’emploie qu’une seule langue. Aussi appelé dictionnaire unilingue.",
"C'est quoi un dictionnaire unilingue ?",
"C'est un ouvrage monofonctionnel qui ne concerne, ne traite et n’emploie qu’une seule langue. Aussi appelé dictionnaire monolingue.",
"C'est quoi un dictionnaire bilingue ?",
"C'est un ouvrage bifonctionnel qui indique les équivalents traductionnels des mots, des expressions de deux langues différentes. Aussi appelé dictionnaire de traduction.",
"C'est quoi un dictionnaire de traduction ?",
"C'est un ouvrage bifonctionnel qui indique les équivalents traductionnels des mots, des expressions de deux langues différentes. Aussi appelé dictionnaire bilingue.",
"C'est quoi un dispositif de fléchage ?",
"Dans des textes, cela renvoie à un ensemble de flèches servant à schématiser le guide d’utilisation d’un dictionnaire donné. Ce guide est inséré au début de l’ouvrage. Il reprend une de ses pages et, telle une instruction, il explicite chacun des composants de ses articles en les liant, par des flèches, aux annotations explicatives avec les composants correspondants. Dans des images, c'est un ensemble de flèches rendant plus saillants les éléments constitutifs d’une illustration, venant enrichir un article. Les dictionnaires encyclopédiques illustrés comme ceux de Larousse en font usage.",
"C'est quoi une définition ?",
"C'est une proposition qui met en équivalence un élément défini et son définissant. Elle a pour but d’expliquer et de clarifier le(s) sens d’un mot ou d’une expression en déterminant ses caractéristiques propres.",
"C'est quoi une définition syntagmatique ?",
"C'est une proposition sous forme de syntagme ou de phrase simple qui commence par l’hyperonyme de l’entrée définie : mot de la même catégorie grammaticale que l’item en adresse et qui partage son sens.",
"C'est quoi une définition morphologique ?",
"C'est une proposition qui exploite la morphologie de l’entrée définie, c’est-à-dire sa construction formelle, son lien avec les mots de la même famille.",
"C'est quoi une définition phrastique ?",
"C'est composé de deux propositions séparées par la copule « c’est ». Ce type de définition s’utilise surtout pour présenter des unités polylexicales qui ne sont jamais en adresse principale ou en adresse subordonnée. Elles apparaissent en italique, comme pour un contexte d’emploi, puisqu’il s’agit d’un patron structurel dont l’item en adresse est l’un des constituants.",
"C'est quoi une définition synonymique ?",
"C'est une proposition qui se contente de donner un synonyme de l’entrée pour la définir, expliquer son sens.",
"C'est quoi une définition métalinguistique ?",
"C'est une proposition qui définit l’entrée en la décrivant elle-même par l’usage de la langue naturelle. ",
"C'est quoi une entrée ?",
"C'est un mot qui sert d’index à chaque article d’un dictionnaire. Il fait partie de l’article et il est l’un des composants de l’adressage qui se distingue souvent par une valorisation typographique spécifique : écriture en gras, de couleur et de taille de police plus grande que le reste de l’article. L’ensemble des entrées apparaît généralement dans l’ordre alphabétique. Il y a plusieurs synonymes : item en adresse, adresse, mot-vedette.",
"C'est quoi un exemple glosé ?",
"C'est une combinaison de deux propositions, l’une contextualisante, l’autre définitoire, les deux séparées par une virgule coordinatrice.",
"C'est quoi un identificateur ?",
"C'est un symbole permettant de structurer et d’organiser les différents éléments d’un article de dictionnaire. Cela concerne tant des signes de ponctuation que des petits dessins ou que des chiffres. Selon la fonction de l’indicateur, il pourra recouvrir plusieurs dénominations.",
"C'est quoi un coordinateur ?",
"C'est un identificateur liant et coordonnant deux éléments. Cela peut s’agir d’une virgule ou, parfois, d’une conjonction de coordination. Il est notamment utilisé pour réunir une forme lemmatique avec sa/ses terminaison(s) flexionnelle(s) ou deux formes graphiques de l’item en adresse.",
"C'est quoi un introducteur ?",
"C'est un identificateur débutant un élément dans le but de le signaler. Cela concerne souvent des symboles. Les introducteurs sont employés pour annoncer des informations assez importantes pour qu’elles soient mises en exergue.",
"C'est quoi un ordonnateur ?",
"C'est un identificateur structurant les informations en les rangeant de manière hiérarchique. Ils peuvent être de nature numérique (chiffres romains, chiffres arabes) ou de nature alphabétique (lettres capitales ou minuscules).",
"C'est quoi un séparateur ?",
"C'est un identificateur disjoignant deux éléments afin de montrer qu’ils sont bien dissociés. Cela est régulièrement matérialisé par des tirets.",
"C'est quoi un terminateur ?",
"C'est un identificateur concluant un élément. Il est souvent matérialisé par un point, à la fin d’un élément textuel, par exemple.",
"C'est quoi la lexicographie ?",
"C'est la discipline qui consiste à recenser les mots, à les classer, à les définir et à les illustrer par des contextualisations, pour rendre compte de l’ensemble de leurs significations et de leurs acceptions au sein d’une langue, afin de constituer un dictionnaire.",
"C'est quoi un lexicographe ?",
"C'est la personne qui écrit, rédige un dictionnaire.",
"C'est quoi une macrostructure ?",
"C'est la liste organisée des entrées d’un dictionnaire et, en conséquence, de ses articles, c’est-à-dire de ses adressages et sous-adressages. Leur nombre, leur disposition et leur nature dépendent du type du dictionnaire et des choix des lexicographes. Il va de soi qu’un dictionnaire spécialisé, argotique, par exemple, aura une macrostructure plus réduite qu’un dictionnaire général.",
"C'est quoi la microstructure ?",
"C'est l'articulation des composants fournis dans les articles d’un dictionnaire. Une logique commune les relie, celle-ci facilitant la lecture. Par exemple, si la transcription phonétique vient après l’item en adresse dans un article, il en est ainsi dans tout le dictionnaire. Les composants constitutifs de la microstructure dépendent de sa visée. De fait, les transcriptions phonétiques mentionnées ci-dessus peuvent ne pas apparaître si l’ouvrage est destiné aux enfants.",
"C'est quoi millésimé ?",
"Cela qualifie un ouvrage dictionnairique édité annuellement et dont l’année de parution est mentionnée dans son titre, constituant, par la même occasion, un argument marketing.",
"C'est quoi un monovolume ?",
"Cela qualifie un ouvrage n’étant décliné qu’en un seul exemplaire. Cela concerne souvent des écrits assez courts pour être contenus dans un seul objet, livre.",
"C'est quoi un plurivolume ?",
"Cela qualifie un ouvrage étant décliné en plusieurs exemplaires. Cela concerne des écrits très longs qu’il est impossible de réduire en un seul exemplaire. Aujourd’hui, il existe encore quelques écrits plurivolumes en version papier mais ils seront préférablement numériques.",
"C'est quoi la métalexicographie ?",
"C'est une discipline universitaire qui étudie les principes et les pratiques guidant l’élaboration de dictionnaires. Elle se situe entre la lexicologie, la lexicographie et la dictionnairique.",
"C'est quoi un renvoi analogique ?",
"Cela concerne  l’item-cible lié morphologiquement à l’item-source par son référent et sens. ",
"C'est quoi un renvoi étymologique ?",
"Cela concerne ’item-cible lié étymologiquement à l’item-source. Ce renvoi se situe principalement dans le composant étymologique de l’article-source.",
"C'est quoi un renvoi synonymique ?",
"Cela concerne l’item-cible est sémantiquement similaire à l’item-source, voire il est son synonyme.",
"C'est quoi un répertoire lexical ?",
"C'est un texte qui associe des données de certaines natures à des éléments lexicaux et qui constitue sa nomenclature tout en permettant la consultation de chaque couple élément/données. Il est considéré comme étant l’objet situé au cœur de la lexicographie, de la terminographie et de la métalexicographie.",
"C'est quoi un répertoire métalinguistique ?",
"C'est un texte qui associe des données de certaines natures à des éléments métalinguistiques, c’est-à-dire à des termes spécialisés pour parler du langage ou de la langue tels que « mot », «verbe », etc. Il permet de consulter chaque couple constitué d’un élément et de données.",
"Que veut dire signification ?",
"C'est la représentation lexicale d’un signe, d’un concept, d’un fait, d’un geste ou d’un objet. Elle peut rendre compte d’un fait concret ou abstrait, comme un propos, un discours ou un texte.",
"C'est quoi la synonymique ?",
"C'est un rapport sémantique proche entre deux mots ; si l’un est remplaçable par l’autre dans un contexte spécifique, l’un s’avère synonyme de l’autre. Deux façons de présenter les synonymes existent dans les dictionnaires : la synonymie cumulative, la plus adoptée de nos jours, suppose un simple enchaînement des synonymes de l’unité linguistique traitée, et la synonymie distinctive délimite les conditions d’emploi de chaque synonyme.",
"C'est quoi la terminographie ?",
"C'est une sous-discipline de la lexicographie qui regroupe un ensemble d’activités dont l’objectif est de décrire des termes relevant de langages non courants dans les dictionnaires spécialisés ou les banques de terminologiques. Elle décrit la terminologie, science traitant des vocabulaires scientifiques ou techniques.",
"C'est quoi une unité linguistique ?",
"C'est l'élément du lexique d’une langue donnée, qui peut être composée d’un ou plusieurs constituants. En métalexicographie, l’emploi du terme « unité linguistique » est préféré à « mot ». Cela permet d’élargir les référents pointés par « mot » tout en employant un vocabulaire plus savant.",
"C'est quoi une unité linguistique monosémique ?",
"C'est un terme ou ensemble de termes n’ayant qu’un sens, qu’une signification, qu’une acception.",
"C'est quoi une unité linguistique polysémique ?",
"C’est un terme ou ensemble de termes ayant plusieurs significations, plusieurs acceptions. ",
"C'est quoi une unité linguistique monolexicale ?",
"Cela réfère au fait qu'un signifiant n'est composé que d’un terme, d’un mot. ",
"C'est quoi une unité linguistique polylexicale ?",
"Cela renvoie au fait qu'un signifiant composé de plusieurs mots tout en restant considéré comme un seul terme, une seule unité linguistique.",
"C'est quoi une veille néologique ?",
"C'est une recherche littéraire, scientifique et bibliographique basée sur des corpus textuels et ayant pour but de trouver de nouvelles entrées à traiter à la nomenclature de la dernière édition d’un dictionnaire. Cette étape est essentielle à la refonte et à la mise à jour d’un ouvrage de référence afin que celui-ci s’inscrive au mieux dans la réalité linguistique actuelle. La fouille s’effectue principalement au travers de corpus journalistiques, de réseaux sociaux, suivant les dernières mouvances, mais aussi d’articles scientifiques pouvant retracer des découvertes majeures devant être dénommées."
])


app = Flask(__name__)
app.static_folder = 'static'


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(bot.get_response(userText))


if __name__ == "__main__":
    app.run()
    
